# Generated by Django 4.2.5 on 2023-09-14 13:21

import configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Key')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Value')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to=configuration.models.config_upload_dir)),
                ('is_public', models.BooleanField(default=False)),
                ('only_admin', models.BooleanField(default=False)),
                ('nullable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
