# Generated by Django 5.0.4 on 2024-05-10 17:36

from django.db import migrations


def delete_tables(apps, schema_editor):
    schema_editor.execute("DROP TABLE IF EXISTS drivers_driver CASCADE;")
    schema_editor.execute("DROP TABLE IF EXISTS owners_owner CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_tables),
    ]
