# Generated by Django 5.0.4 on 2024-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_owner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
