# Generated by Django 5.0.4 on 2024-06-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_supplystorage_supply'),
        ('base', '0007_alter_client_observation_alter_supplier_observation'),
    ]

    operations = [
    ]
