# Generated by Django 5.0.4 on 2024-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks'),
        ),
    ]
