# Generated by Django 5.0.4 on 2024-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_supplier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trailers'),
        ),
    ]
