# Generated by Django 5.0.4 on 2024-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_client_status_client_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
