# Generated by Django 5.0.4 on 2024-07-08 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_owner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
