# Generated by Django 5.0.4 on 2024-06-18 20:10

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_alter_trailer_chassis_alter_trailer_plate_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_number', models.CharField(max_length=50, unique=True)),
                ('loading_date', models.DateField()),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_mcu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fob_value_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3)),
                ('fob_value', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=15)),
                ('successive_carriers', models.TextField(blank=True, null=True)),
                ('external_freight_amount_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3)),
                ('external_freight_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15)),
                ('reimbursement_amount_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3)),
                ('reimbursement_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15)),
                ('contains', models.TextField()),
                ('customs_instructions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sender_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_crts', to='base.client')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignee_crts', to='base.client')),
                ('destination_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_crts', to='cities_light.city')),
                ('loading_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_crts', to='cities_light.city')),
                ('notify_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notify_crts', to='base.client')),
                ('place_of_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_crts', to='cities_light.city')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_crts', to='base.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_crts', to='base.client')),
            ],
            options={
                'ordering': ['crt_number'],
            },
        ),
        migrations.CreateModel(
            name='CRTExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15)),
                ('crt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.crt')),
            ],
        ),
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
        ),
        migrations.CreateModel(
            name='DTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transito_aduanero', models.BooleanField(blank=True, null=True)),
                ('carrier_rol_del_contribuyente', models.CharField(blank=True, max_length=255, null=True)),
                ('MIC_DTA_number', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('destination_code', models.PositiveIntegerField(blank=True, null=True)),
                ('truck_owner_rol_del_contribuyente', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_model', models.CharField(blank=True, max_length=255, null=True)),
                ('towing_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_year', models.DateField(blank=True, null=True)),
                ('is_semi_trailer', models.BooleanField(blank=True, null=True)),
                ('trailer_license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_truck_owner_rol_del_contribuyente', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_truck_license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_brand_model', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_towing_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute_truck_year', models.DateField(blank=True, null=True)),
                ('substitute_is_semi_trailer', models.BooleanField(blank=True, null=True)),
                ('substitute_trailer_license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('carta_de_porte_number', models.CharField(blank=True, max_length=255, null=True)),
                ('FOT_value_and_currency_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3, null=True)),
                ('FOT_value_and_currency', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15, null=True)),
                ('origen_mercancias_code', models.CharField(blank=True, max_length=3, null=True)),
                ('freight_in_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance_in_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_type_code', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attached_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_p', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_description_code', models.CharField(blank=True, max_length=10, null=True)),
                ('carrier_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_signature_date', models.DateField(blank=True, null=True)),
                ('customs_signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('customs_signature_date', models.DateField(blank=True, null=True)),
                ('DTA_number', models.CharField(blank=True, max_length=255, null=True)),
                ('DTA_route', models.CharField(blank=True, max_length=255, null=True)),
                ('DTA_ETA', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_carrier', to='base.client')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_consignee', to='base.client')),
                ('departure_customs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_departure_customs', to='trips.customs')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_destination_city', to='cities_light.city')),
                ('destination_customs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_destination_customs', to='trips.customs')),
                ('origen_mercancias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_origen_mercancias', to='cities_light.city')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_recipient', to='base.client')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_sender', to='base.client')),
                ('substitute_truck_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_substitute_truck_owner', to='base.owner')),
                ('truck_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_truck_owner', to='base.owner')),
            ],
        ),
    ]
