# Generated by Django 5.0.4 on 2024-06-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_trailer_chassis_alter_trailer_plate_and_more'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dta',
            name='driver_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DTA_primary_driver', to='base.driver'),
        ),
        migrations.AddField(
            model_name='dta',
            name='driver_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DTA_secondary_driver', to='base.driver'),
        ),
        migrations.AddField(
            model_name='dta',
            name='extra_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dta',
            name='extra_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
