# Generated by Django 5.0.4 on 2024-06-26 13:19

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20240624_1409'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('invoice', '0003_supplierinvoice_payment_term_supplierinvoiceitem'),
        ('trips', '0006_crtexpense_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dta',
            name='DTA_route',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='FOT_value_and_currency',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='FOT_value_and_currency_currency',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='cargo_quantity',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='cargo_type',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='cargo_type_code',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='carta_de_porte_number',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='destination_customs',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='driver_1',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='driver_2',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='freight_in_usd',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='insurance_in_usd',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='origen_mercancias',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='origen_mercancias_code',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='dta',
            name='sender',
        ),
        migrations.AddField(
            model_name='dta',
            name='carrier_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dta',
            name='customs_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='export_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_crts', to='invoice.supplierinvoice'),
        ),
        migrations.AlterField(
            model_name='dta',
            name='departure_customs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_departure_customs', to='cities_light.city'),
        ),
        migrations.CreateModel(
            name='DTAShipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_of_lading', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_goods_code', models.CharField(blank=True, max_length=3, null=True)),
                ('FOT_value_and_currency_currency', djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3, null=True)),
                ('FOT_value_and_currency', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15, null=True)),
                ('freight_in_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance_in_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_type_code', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contains', models.TextField()),
                ('DTA_route', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_consignee', to='base.client')),
                ('destination_customs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_destination_customs', to='cities_light.city')),
                ('driver_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DTA_primary_driver', to='base.driver')),
                ('driver_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DTA_secondary_driver', to='base.driver')),
                ('dta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_details', to='trips.dta')),
                ('export_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_dta', to='invoice.supplierinvoice')),
                ('origin_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_origen_mercancias', to='cities_light.city')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_recipient', to='base.client')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_sender', to='base.client')),
            ],
        ),
    ]
