# Generated by Django 5.0.4 on 2024-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_dta_dta_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crt',
            name='carrier',
        ),
        migrations.AlterField(
            model_name='crt',
            name='consignee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='notify_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
