# Generated by Django 5.0.4 on 2024-07-04 19:37

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_remove_crt_carrier_alter_crt_consignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crt',
            name='cif_name',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='cif_value',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='cif_value_currency',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='export_invoice',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='fob_name',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='fob_value',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='fob_value_currency',
        ),
        migrations.RemoveField(
            model_name='crt',
            name='sender_signature',
        ),
        migrations.RemoveField(
            model_name='crtexpense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='crtexpense',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='crtexpense',
            name='checked',
        ),
        migrations.AddField(
            model_name='crt',
            name='attached_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crt',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crt',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crt',
            name='carrier_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crt',
            name='load_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='crt',
            name='load_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='crt',
            name='merchandise_value_1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='crt',
            name='merchandise_value_1_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='crt',
            name='merchandise_value_2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='crt',
            name='merchandise_value_2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='crt',
            name='type_merchandise_1',
            field=models.IntegerField(choices=[(1, 'FOB'), (2, 'CIF')], null=True),
        ),
        migrations.AddField(
            model_name='crt',
            name='type_merchandise_2',
            field=models.IntegerField(choices=[(1, 'FOB'), (2, 'CIF')], null=True),
        ),
        migrations.AddField(
            model_name='crtexpense',
            name='recipient_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='crtexpense',
            name='recipient_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='crtexpense',
            name='sender_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='crtexpense',
            name='sender_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='crt',
            name='destination_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='loading_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crt',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
