# Generated by Django 5.0.4 on 2024-07-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_crt_cif_name_remove_crt_cif_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRTIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration', models.PositiveIntegerField(max_length=4)),
                ('year', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DTAIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration', models.PositiveIntegerField(max_length=4)),
                ('year', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
