# Generated by Django 5.0.4 on 2024-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_crtindex_dtaindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crtindex',
            name='enumeration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crtindex',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dtaindex',
            name='enumeration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dtaindex',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
