# Generated by Django 5.0.4 on 2024-05-08 02:39

from django.db import migrations

def generate_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='Admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [migrations.RunPython(generate_groups)]
