# Generated by Django 5.0.4 on 2024-07-08 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
