# Generated by Django 5.0.4 on 2024-05-23 14:33

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='outstanding_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PYG', max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='outstanding_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='PYG', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='paid_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PYG', max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='paid_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='PYG', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PYG', max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('USD', 'US Dollar'), ('UYU', 'Uruguayan Peso')], default='PYG', editable=False, max_length=3),
        ),
    ]
